# conda deactivate
# conda env remove --name mario_rl
# conda env create --file environment.yml
# conda activate mario_rl
#
# conda deactivate && conda env remove --name mario_rl -y && conda env create --file environment.yml -y && conda activate mario_rl
#
# tensorboard --logdir runs

name: mario_rl

channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - pytorch::pytorch
  - tensorboard
  - tensordict
  - matplotlib
  - ffmpeg
  # numpy <2.0.0 permits to avoid the "OverflowError: Python integer 1024 out of bounds for uint8" in nes_py
  # see https://stackoverflow.com/questions/78757000/overflowerror-when-setting-up-gym-super-mario-bros-environment-in-python-on-jupy
  - numpy<2.0.0
  - conda-forge::pygraphviz
  # conda-forge::gymnasium=1.0.0
  - pip
  - pip:
      - gym_super_mario_bros==7.4.0
      - gym==0.23.1
      - torchrl==0.5
      - opencv-python
      - lz4
      # for video export
      - scikit-video
      - tomli
      - neat-python
      - wandb
      - python-dotenv
      - ruff