# conda deactivate
# conda env remove --name mario_rl
# conda env create --file environment.yml
# conda activate mario_rl
#
# conda deactivate && conda env remove --name mario_rl_py3.11 && conda env create --file environment.yml && conda activate mario_rl_py3.11
#
# tensorboard --logdir runs

name: mario_rl_py3.11

channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - pytorch::pytorch
  - tensorboard
  - tensordict
  - matplotlib
  - ffmpeg
  - conda-forge::pygraphviz
  - pip
  - pip:
      - gym_super_mario_bros==7.4.0
      - gym==0.23.1
      - torchrl==0.3
      - opencv-python
      - lz4
      # for video export
      - scikit-video
      - tomli
      - neat-python
      - wandb
      - python-dotenv
