seed = 0
debug = true
use_gpu = true

# save freq in episodes
use_save_states = true
save_states_freq = 10

# env_name: 'CartPole-v1', 'SuperMarioBros-1-1-v3'
ENV_NAME = "SuperMarioBros-1-1-v3"

# algo: NEAT, DQNN, REINFORCE, DPO
algo = "NEAT"

# algorithms config files
neat_config_file = "neat_config.v6.cfg"
dpo_config_file = "dpo_config.toml"
reinforce_config_file = "reinforce_config.toml"
dqnn_config_file = "dqnn_config.toml"

# loggers
start_tensorboard = false
start_wandb = true
